language: node_js
node_js:
  - 8
cache:
  yarn: true
jobs:
  include:
    - stage: initial
      script: yarn run lint
      script: yarn run test
      script: yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
