language: node_js
node_js:
  - 8
cache:
  yarn: true
jobs:
  include:
    - stage: checks
      script: yarn run lint
    - script: yarn run test
    - script: yarn run build
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
stages:
  - checks
  - name: deploy
    if: branch = master
