language: node_js
node_js:
  - 8
cache:
  yarn: true
jobs:
  include:
    - stage: checks
    - script: yarn run lint
      env: JOB=lint
    - script: yarn run test
      env: JOB=test
    - script: yarn run build
      env: JOB=build
    - stage: deploy
      env: JOB=deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
stages:
  - checks
  - name: deploy
    if: branch = master
